# Generated by Django 3.0.8 on 2020-07-30 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(choices=[('E', 'Electricity'), ('G', 'Gas'), ('W', 'Water')], default='E', max_length=3)),
                ('unit', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MeterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trialProjApp.Meter')),
            ],
        ),
    ]
